### ISSUE TITLE
коммент

### ISSUE THREAD

**Issue by leeiozh** [mickafa/FALT_2#1]
Моё почтение, оформление - просто заглядение

Замечаний мало, по первому пункту уже сам знаешь что править и над чем работать, но
а) Схема раскрытия/закрытия дико нестандартная и поэтому, как мне кажется, время полета сильно завышено. Игрался ли с другими phi_open и phi_close (понимаю, что игрался, но почему пришел к таким)?
б) До Луны долетел - потрясающе. А теперь посмотри на свою скорость на подлете и вычисли первую комическую для Луны в нашей СО. Сделай выводы. Сейчас добавлю доп условие, что можно будет сбросить скорость на подлете
в) Шаг по времени можно регулировать. Прямо нужно. Промежуточные орбиты можешь считать хоть с 20с, но последний виток лучше точнее, чем 5с брать
г) Хочешь ускорить - не делай репорты в printf, сразу сохраняй в отдельный csv

В целом - кайфово. Условие на сброс скорости у Луны докину, без него это действительно ювелирная работа)

**Comment by mickafa** [comment]
Спасибо за отзыв! Очень приятно получить.
На мой взгляд, вторая задача на порядок сложнее первой. (Или я просто стал более придирчив). И оказалась очень залипательная, к сожалению для меня. 

Да, решение состоит из набора кривых костылей, неустойчиво подпирающих друг друга. Пробовал много вариантов схем управления парусом. Постарался, чтобы то, что я выложил, показывало ситуацию наиболее конкретно. Конечно, это не решение в нормальном понимании.

Думаю, что с парусом есть принципиальная физическая проблема, более серьёзная, чем медленный набор скорости. Увеличение шага DT не поможет. Введение условия торможения на последнем витке тоже не имеет смысла, оно тоже не даст качественного решения. Я на выходных подробнее напишу почему так считаю, и предложу вариант как преодолеть проблему

**Comment by mickafa** [comment]
Написал оправдалку - добавил .doc файл в репозиторий - история работы с задачей, и к чему в итоге пришёл.
Или мой вывод неправильный?

**Comment by leeiozh** [comment]
Оправдалка засчитана. Вероятно то, что у нас получалось достичь орбиты - это просто удача. Очень здорово, что ты настолько глубоко погрузился в эту задачу и сейчас единственным верным решением, на мой взгляд, будет на нее забить. И заботать третий пункт, порешать следующий туры.
Если никто из участников не предоставит лучшего решения, то в конце поднимем твои баллы за эту задачу до фулла, а пока оставим потенциальный запас на доработки.

**Comment by mickafa** [comment]
Я дико извиняюсь, но я не смог отлипнуть от задачи и загрузил второе решение. Это не ради баллов, а чисто из интереса, и Крыс грустил, что не долетел. Применил двигатель, поэтому решение не соответствует условию, но траектория получилась красивая, код проще - костыли выкинул, алгоритм управления парусом принципиально другой. Это (второе) решение описано в трёх файлах 22.*  :    .docx - описание, .xlsx - графики, .cpp - код. Догрузил три этих новых файла в репозиторий.
В решении много непонятных констант - все они получены чисто подбором

**Comment by leeiozh** [comment]
Воот, теперь схема управления парусом стала более очевидной. Траектория выглядит правдоподобно. Конечно, моментальный импульс без потерь это то еще упрощение, но к основной морали ты уже давно и сам подобрался - здесь играет чистый подбор. А графичек твой я, пожалуй, сохраню)
Ставлю фулл лишь бы ты уже пошел решать следующие туры. Второй тур начат хорошо, решение верное, но его проверяет другой человек, поэтому возможны длительные задержки с баллами.

**Comment by mickafa** [comment]
Порешал остальные туры. Некоторые задачи не понял, некоторые понял неправильно, что смог - решил в меру понимания. Из всех них ни одна не привлекла внимание так, как эта. Эта затягивает. Попробую вернуться к паруснику. 

https://github.com/mickafa/FALT_2/blob/main/23_план_третьего_полёта.docx

**Comment by leeiozh** [comment]
А почему все-таки бриг, а не шхуна?(
Смотри, по остальным турам ты точно нарешал на проход на закл, так что развлекайся с этой _в меру сил и времени_.
По второму туру - он неочевидный с точки зрения формулировки задач (как и все задачи фалтов). Четвертый тур по условию еще более сырой чем второй, ты там написал верные мысли, ответы не сходятся, но пусть там уже разбирается ответственный от фалтов. Из забавного - над капельным охлаждением как раз работала моя лаборатория факишников, но задачу эту предложили фалты. А еще мы так видеолекций от них не получили, мб поэтому какие-то вещи остались непонятыми.
Отвечая на неотвеченный вопрос - нет у меня карты. Есть код, мб посижу, покручу, но не то, чтобы было время на это. Сессия как никак. Так если посмотреть - именно в первый тур мы вложили все силы и идеи, третий скорее как остатки моего астрономического олимпиадного прошлого родился. На закле постараюсь раскачать мудрых людей, задачи будут повкуснее.

**Comment by mickafa** [comment]
С новым годом! С новой сессией! :)
Постарался найти маршрут получше. Всё-таки не нашёл траектории выхода на орбиту Луны без двигателя. Но также и не могу доказать, что такой траектории не существует. В чём проблема: орбита парусника получается слишком вытянутой, перигей близко к высоте геостационарной орбиты. Из-за этого скорость парусника в апогее слишком низкая, порядка 250 – 300 м/с, а Луна имеет скорость порядка 1000 м/с. При таком соотношении Луна тупо проскакивает мимо. 
Может быть можно с очень высокой точностью попасть на совсем низкую высоту, чтобы относительная скорость получилась меньше 1-й космической, но не с нашими возможностями получить такую точность. Думаю, практически запускать аппарат к Луне без двигателя нереально и бессмысленно.
Но на второй вопрос: можно ли парусом понизить окололунную орбиту, ответ – «да, можно». Нужно открывать парус на торможение в периселении в момент, когда Солнце расположено удачно. Это процесс небыстрый, занимает годы, но принципиально работает. Алгоритм простой.
Траектория - в эксельке 23.xlsx, добавил её в репозиторий. https://github.com/mickafa/FALT_2/blob/main/23.xlsx 

Почему не шхуна? Если использовать косой парус, то можно в каких-то пределах регулировать направление вектора тяги, но несильно, т.к. тяга паруса при повороте очень уж падает. Но принципиально, наверное, с косым парусом можно получить более круглую орбиту. Не пробовал, потому что добавляется ещё один параметр, поэтому алгоритм управления сильно усложнится. Я не упоролся до такой степени. 
И не упоролся, чтобы полететь на парусе на Марс, хотя такая хотелка сначала была.

Решение задачи про капельное охлаждение перепроверил, ошибки не вижу. Думаю, что радиус капли 0,035 мм – это правильный ответ на задачу при этих исходных данных. Но да, это трудно назвать каплей, скорее пыль какая-то. Вообще, идея такой системы охлаждения очень странная, олово будет теряться, испаряться. Если бы я как инженер делал реальный проект, то открытую систему не использовал бы, т.к. слишком много неизвестных, непонятно ни разу как её протестировать. Первая идея – сделать тоннель вокруг потока капель из материала, хорошо пропускающего излучение, тогда не нужно решать проблему с всасыванием капель из вакуума. Но рано или поздно олово покроет стенки тоннеля изнутри, и в итоге придём к обычному радиатору.

Ещё одна идея – создать между форсунками и ловушкой капель разность потенциалов, например, вольт в тысячу, тогда капли будут притягиваться к ловушке за счёт электростатики. Но: вдруг однажды из капель получится неразрывная струя (дорожка), тогда систему закоротит. В общем, по-моему, на практике идея неработоспособная.
